# YAML file for Paperspace Gradient NLP Text Generation Tutorial example
# It runs the GPT-2 model from HuggingFace: https://huggingface.co/gpt2
#
# The Workflow is triggered when this is present in the .gradient/workflows/ directory in a GitHub
# repository linked to the user's Gradient project
# It clones this repo and then in turn calls the file nlp_text_generation.py
# This file outputs the generated text to outputs.txt in a Gradient-managed Dataset
# This Workflow runs on the Paperspace HuggingFace NLP container (paperspace/transformers-gpu:0.4.0)
#
# See the Gradient documentation page for more details:
# https://docs.paperspace.com/gradient/get-started/tutorials-list/example-workflow-nlp-text-generator
#
# Last updated: Nov 03rd 2021

on:
  github:
    branches:
      only: main

jobs:

  cloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
      ref: context.event.github.ref

  generateText:
    resources:
      instance-type: P4000
    needs:
      - cloneRepo
    inputs:
      repo: cloneRepo.outputs.repo
    outputs:
      generatedText:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run
        curl -fsSL https://code-server.dev/install.sh | sh
        timeout 2s code-server
        cd ~/.config/code-server
        cat config.yaml
        npm install -g localtunnel
        code-server --bind-addr 127.0.0.1:8040  & lt --port 8040
      image: paperspace/transformers-gpu:0.4.0

# Appendix: Extra details
